Feat:  add sorting by name
sparkbox/apprenticeship-sparkhero pull request #10
Opened 2022-09-19 18:30 UTC by jkohrt7

### Description
- Add getCharactersSortedByName to characterSort.js, a function that takes a Character array and returns it with the characters sorted by their name property (starting with A).
- Add this function under the `name` case in getSortedCharacters' switch statement.
- Add new tests for getSortedCharacters to characterSort.spec.js
- Moved a misplaced filter test from the characterSort.spec file to the characterFilters.spec file (possibly needs its own pr)

### Spec

See Story: [FSA22V2-90](https://sparkbox.atlassian.net/browse/FSA22V2-90)

### Validation

* [ ] This PR has code changes, and our linters still pass.
* [ ] This PR has new code, so new tests were added and updated, and they pass.

#### To Validate

1. Make sure all PR Checks have passed (GitHub Actions, CircleCI, Code Climate, etc).
2. Pull down the branch `feat--getSortedCharacters` and install dependencies with `npm i`.
3. Confirm all tests pass with `npm run test`.

2022-09-19 18:36 UTC, jkohrt7 commented
I'm actually going to make a fix branch specifically for the tests first, then reopen this.

2022-09-19 19:45 UTC, jkohrt7 commented
The close/reopen was because I wasn't sure if the test refactoring and bug fixing should be its own PR. 

Decided after closing that it's minor enough to be included here and reopened this PR.

2022-09-20 16:04 UTC, theogainey requested changes
Looks good but before I approve I want you to take a look at my comment about testing. If you have a good reason why they should be left as is just let me know and I can unrequest changes

2022-09-20 17:27 UTC, jkohrt7 commented on src/js/utilities/characterSort.spec.js
> +function createTestArray() {
Can't take credit for this--it was Jon's idea to use a helper to avoid the mutation problems I was having before!

2022-09-20 18:39 UTC, jkohrt7 commented on src/js/utilities/characterFilters.spec.js
>  describe('characterFilters.js', () => {
Refactored the tests to loop through the arrays. The "Should return an array of characters filtered by publisher"  it statement on lines 50-54, for example, now looks like 
```
    filteredList.forEach((element) => {
      expect(element.biography.publisher).toBe('Marvel Comics');
    });
```

2022-09-20 19:48 UTC, theogainey approved these changes
![](https://acegif.com/wp-content/uploads/gif-good-job-80.gif)

2022-09-20 21:55 UTC, merged